[protocol]
name = "ecommerce-payments"
scope = ""
version = "0.0.0"
description = ""
main = "main.tx3"

[ledger]
family = "cardano"

[[codegen]]
plugin = "ts-client"
output_dir = "../src/lib/tx3"
ref = "codegen-v1beta0"

[profiles.local]
network = "CardanoDevnet"

[profiles.local.trp]
url = "http://localhost:8164"

[profiles.preview]
network = "CardanoPreview"

[profiles.preview.trp]
url = "https://trp.preview.txpipe.io"
